apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  labels:
    app: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - image: asia-south1-docker.pkg.dev/sleepr-430609/notifications/production
          name: notifications
          env:
            - name: PORT
              value: '3000'
            - name: SMTP_USER
              value: itissumitsingh@gmail.com
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: 661902510228-fr6d01knq03inn3d00a75qmq3avep7c9.apps.googleusercontent.com
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: GOOGLE_OAUTH_CLIENT_SECRET
            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google
                  key: GOOGLE_OAUTH_REFRESH_TOKEN
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: '500m'
              memory: '256Mi'
            limits:
              cpu: '1000m'
              memory: '512Mi'
