apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/sleepr-430609/payments/production
          name: payments
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '100m'
              memory: '128Mi'
