apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/sleepr-430609/auth/production
          name: auth
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '100m'
              memory: '128Mi'
