// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.0.3
//   protoc               v3.21.12
// source: proto/payments.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

// export const protobufPackage = "payments";

export interface CreateChargeResponse {
  id: string;
}

export interface CreateChargeMessage {
  email: string;
  amount: number;
  card: CardMessage | undefined;
}

export interface CardMessage {
  cvc: string;
  expMonth: number;
  expYear: number;
  number: number;
}

export const PAYMENTS_PACKAGE_NAME = 'payments';

export interface PatmentsServiceClient {
  createCharge(request: CreateChargeMessage): Observable<CreateChargeResponse>;
}

export interface PatmentsServiceController {
  createCharge(
    request: CreateChargeMessage,
  ): Promise<CreateChargeResponse> | Observable<CreateChargeResponse> | CreateChargeResponse;
}

export function PatmentsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['createCharge'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('PatmentsService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('PatmentsService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PATMENTS_SERVICE_NAME = 'PatmentsService';
