apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
  labels:
    app: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - image: asia-south1-docker.pkg.dev/sleepr-430609/reservations/production
          name: reservations
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGO_URI
          resources:
            requests:
              cpu: '500m'
              memory: '256Mi'
            limits:
              cpu: '1000m'
              memory: '512Mi'
