apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
  labels:
    app: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/sleepr-430609/reservations/production
          name: reservations
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '100m'
              memory: '128Mi'
      restartPolicy: Always
      imagePullPolicy: Always
